"""Store boundary; composition installs the persistence implementation."""

from collections.abc import Callable
from typing import Protocol

from itinerary.domain import DayData, EntryData, NoteData


class Store(Protocol):
    def entries(self, trip_id: str) -> list[EntryData]: ...
    def days(self, trip_id: str) -> list[DayData]: ...
    def notes(self, trip_id: str) -> list[NoteData]: ...
    def get_entry(self, entry_id: str) -> EntryData | None: ...
    def get_note(self, note_id: str) -> NoteData | None: ...
    def save_day(self, trip_id, day, fields) -> DayData: ...
    def save_entry(self, trip_id, actor_id, fields, entry_id=None) -> EntryData: ...
    def move_entry(self, entry_id, direction) -> DayData: ...
    def delete_entry(self, entry_id) -> None: ...
    def save_note(self, trip_id, actor_id, fields, note_id=None) -> NoteData: ...
    def delete_note(self, note_id) -> None: ...
    def copy_proposal(self, proposal_id, trip_id, actor_id, day, fields) -> None: ...
    def remove_tray_proposal(self, proposal_id) -> None: ...


_factory: Callable[[], Store] | None = None


def configure(factory):
    global _factory
    _factory = factory


def default_store() -> Store:
    if _factory is None:
        raise RuntimeError("itinerary store is not configured")
    return _factory()
