# Generated by Django 5.2.17 on 2026-10-01 18:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinkPreview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                ("canonical_url", models.CharField(max_length=2000, unique=True)),
                ("final_url", models.URLField(blank=True, default="", max_length=2000)),
                ("site_name", models.CharField(blank=True, default="", max_length=200)),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("image_url", models.URLField(blank=True, default="", max_length=2000)),
                (
                    "thumb_file",
                    models.ImageField(blank=True, null=True, upload_to="linkpreview/thumbs/"),
                ),
                (
                    "price_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "price_currency",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                (
                    "lat",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "lng",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "fetch_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ok", "Ok"),
                            ("partial", "Partial"),
                            ("blocked", "Blocked"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "fetch_error",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("fetch_attempts", models.PositiveSmallIntegerField(default=0)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["fetch_status"], name="linkpreview_fetch_s_ada939_idx")
                ],
            },
        ),
    ]
