# Generated by Django 5.2.17 on 2026-10-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("code_hmac", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("ip", models.CharField(blank=True, max_length=45)),
                ("eligible", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["phone", "created_at"],
                        name="identity_ot_phone_447b15_idx",
                    ),
                    models.Index(fields=["ip", "created_at"], name="identity_ot_ip_a4343e_idx"),
                    models.Index(fields=["created_at"], name="identity_ot_created_7878b9_idx"),
                ],
            },
        ),
    ]
