# Generated by Django 5.2.17 on 2026-10-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_otp_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="tour_seen_version",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
