from contextlib import AbstractContextManager
from typing import Any, Protocol


class TaskStore(Protocol):
    def atomic(self) -> AbstractContextManager: ...
    def get(self, task_id: str, *, lock: bool = False) -> dict[str, Any] | None: ...
    def create(
        self, trip_id: str, actor_id: str | None, fields: dict[str, Any]
    ) -> dict[str, Any]: ...
    def update(self, task_id: str, fields: dict[str, Any]) -> dict[str, Any]: ...
    def delete(self, task_id: str) -> None: ...
