# Generated by Django 5.2.17 on 2026-10-01 18:14

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resort",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "country",
                    models.CharField(choices=[("AR", "Ar"), ("CL", "Cl")], max_length=2),
                ),
                ("region", models.CharField(blank=True, default="", max_length=80)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("base_elev_m", models.PositiveSmallIntegerField()),
                ("summit_elev_m", models.PositiveSmallIntegerField()),
                ("timezone", models.CharField(max_length=64)),
                (
                    "provider",
                    models.CharField(
                        choices=[("open_meteo", "Open Meteo"), ("manual", "Manual")],
                        default="open_meteo",
                        max_length=16,
                    ),
                ),
                (
                    "provider_ref",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("website_url", models.URLField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["country", "name"],
                "indexes": [
                    models.Index(fields=["country", "active"], name="ski_resort_country_active")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("summit_elev_m__gt", models.F("base_elev_m"))),
                        name="ski_resort_summit_above_base",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SkiProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("ski", "Ski"),
                            ("snowboard", "Snowboard"),
                            ("both", "Both"),
                        ],
                        default="ski",
                        max_length=12,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("first_time", "First Time"),
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=12,
                    ),
                ),
                ("owns_gear", models.BooleanField(default=False)),
                (
                    "boot_size_eu",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(230),
                        ],
                    ),
                ),
                (
                    "weight_kg",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(25),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                ("share_sizes_with_trip", models.BooleanField(default=False)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ski_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SnowFetchState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "resort",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fetch_state",
                        to="ski.resort",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GearPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.CharField(
                        choices=[
                            ("skis", "Skis"),
                            ("board", "Board"),
                            ("boots", "Boots"),
                            ("poles", "Poles"),
                            ("helmet", "Helmet"),
                            ("goggles", "Goggles"),
                            ("jacket", "Jacket"),
                            ("pants", "Pants"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("own", "Own"),
                            ("rent", "Rent"),
                            ("borrow", "Borrow"),
                        ],
                        default="own",
                        max_length=8,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gear_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gear_plans",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "person", "item"), name="ski_unique_gear_item"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LiftPass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product", models.CharField(blank=True, default="", max_length=120)),
                ("days", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("needed", "Needed"),
                            ("bought", "Bought"),
                            ("season_pass", "Season Pass"),
                            ("not_needed", "Not Needed"),
                        ],
                        default="needed",
                        max_length=12,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lift_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lift_passes",
                        to="trips.trip",
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ski.resort",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "person", "resort"),
                        name="ski_unique_pass_per_resort",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("resort__isnull", True)),
                        fields=("trip", "person"),
                        name="ski_unique_resort_less_pass",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SnowReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("open_meteo", "Open Meteo"), ("manual", "Manual")],
                        max_length=16,
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField()),
                (
                    "elevation_m",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("base_cm", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "new_24h_cm",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                (
                    "forecast_72h_cm",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                (
                    "temp_c",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                ("lifts_open", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "lifts_total",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("runs_open", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("runs_total", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status_text",
                    models.CharField(blank=True, default="", max_length=280),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="ski.resort",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at"],
                "indexes": [
                    models.Index(
                        fields=["resort", "-observed_at"],
                        name="ski_report_resort_observed",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TripResort",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nights", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip_links",
                        to="ski.resort",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ski_resorts",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "resort"), name="ski_unique_trip_resort"
                    )
                ],
            },
        ),
    ]
