# Generated by Django 5.2.17 on 2026-10-01 18:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "answer",
                    models.CharField(
                        choices=[("yes", "Yes"), ("maybe", "Maybe"), ("no", "No")],
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_responses",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["trip", "date"], name="availability_trip_date_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "person", "date"),
                        name="unique_availability_per_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(choices=[("dates", "Dates")], default="dates", max_length=16),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=8,
                    ),
                ),
                ("window_start", models.DateField()),
                ("window_end", models.DateField()),
                ("min_days", models.PositiveSmallIntegerField()),
                ("max_days", models.PositiveSmallIntegerField()),
                (
                    "maybe_weight",
                    models.DecimalField(decimal_places=2, default="0.50", max_digits=3),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("outcome_start", models.DateField(blank=True, null=True)),
                ("outcome_end", models.DateField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["trip", "status"], name="decision_trip_status_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "dates"), ("status", "open")),
                        fields=("trip",),
                        name="one_open_dates_decision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("window_end__gte", models.F("window_start"))),
                        name="decision_window_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("min_days__gte", 1), ("min_days__lte", 60)),
                        name="decision_min_days_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_days__gte", models.F("min_days")),
                            ("max_days__lte", 60),
                        ),
                        name="decision_max_days_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("maybe_weight__gte", 0), ("maybe_weight__lte", 1)),
                        name="decision_maybe_weight_range",
                    ),
                ],
            },
        ),
    ]
