import manifest from "./manifest.json";

/** What a trip's place looks like. Seven photo scenes; the four illustrations/clips are coarser. */
export type PhotoScene = "snow" | "lake" | "beach" | "vineyard" | "desert" | "city" | "road";
export type BannerKind = "logistics" | "map" | "planner";

export type PhotoVariant = { src: string; width: number; height: number };

export type Photo = {
  id: string;
  /** Smallest first. */
  variants: PhotoVariant[];
  /** CSS object-position of the focal point, when the photo is cropped (portraits in a landscape frame). */
  position?: string;
  credit: { author: string; source: string; license: string };
};

type Entry = Omit<Photo, "id"> & { scene?: PhotoScene; banner?: BannerKind; orientation: "landscape" | "portrait" };

// manifest.json is generated by `pnpm photos:build` (scripts/photos/build.mjs).
const entries = Object.entries(manifest.photos as Record<string, Entry>)
  .map(([id, entry]) => ({ ...entry, id }))
  .sort((a, b) => a.id.localeCompare(b.id));

const toPhoto = ({ id, variants, position, credit }: Entry & { id: string }): Photo => ({ id, variants, position, credit });

/** Every photo of a scene, in a stable order. */
export function scenePhotos(scene: PhotoScene): Photo[] {
  return entries.filter((entry) => entry.scene === scene).map(toPhoto);
}

/** FNV-1a: tiny, stable across runtimes, spreads ids over a handful of buckets. */
export function hashSeed(value: string): number {
  let result = 0x811c9dc5;
  for (let index = 0; index < value.length; index += 1) {
    result ^= value.charCodeAt(index);
    result = Math.imul(result, 0x01000193) >>> 0;
  }
  return result;
}

/** The photo a seed (a trip id) gets in a scene: always the same one, `null` when the scene has none. */
export function pickScenePhoto(scene: PhotoScene, seed: string): Photo | null {
  const photos = scenePhotos(scene);
  return photos.length === 0 ? null : photos[hashSeed(seed) % photos.length];
}

/** The banner photo of a section, or `null` when there is none. */
export function bannerPhoto(kind: BannerKind): Photo | null {
  const entry = entries.find((candidate) => candidate.banner === kind);
  return entry ? toPhoto(entry) : null;
}

/**
 * The attributes of an `<img>` for a photo: the full srcset by default, or only the smallest variant
 * when the person asked to save data. `width` and `height` are the largest variant's, so the browser
 * reserves the right ratio before the file arrives.
 */
export function photoImage(photo: Photo, { small = false }: { small?: boolean } = {}) {
  const smallest = photo.variants[0];
  const largest = photo.variants[photo.variants.length - 1];
  if (small) return { src: smallest.src, srcSet: undefined, width: smallest.width, height: smallest.height };
  return {
    src: largest.src,
    srcSet: photo.variants.map((variant) => `${variant.src} ${variant.width}w`).join(", "),
    width: largest.width,
    height: largest.height,
  };
}
