from contextlib import AbstractContextManager
from typing import Protocol


class DocumentStore(Protocol):
    def atomic(self) -> AbstractContextManager: ...
    def create(self, trip_id, person_id, data, mime, name, digest, fields, quota): ...
    def update(self, document_id, fields): ...
