# Generated by Django 5.2.17 on 2026-10-01 19:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("proposals", "0001_initial"),
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItineraryDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("title", models.CharField(default="", max_length=120)),
                ("notes", models.TextField(default="", max_length=2000)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary_days",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItineraryEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("activity", "activity"),
                            ("transport", "transport"),
                            ("lodging", "lodging"),
                            ("meal", "meal"),
                            ("meeting", "meeting"),
                            ("ski", "ski"),
                            ("other", "other"),
                        ],
                        default="activity",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location_label", models.CharField(default="", max_length=200)),
                (
                    "lat",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "lng",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("is_meeting_point", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "manual"), ("proposal", "proposal")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(default="", max_length=1000)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="itinerary.itineraryday",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="proposals.proposal",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="trips.trip"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(max_length=1000)),
                ("pinned", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="trips.trip"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="itineraryday",
            constraint=models.UniqueConstraint(
                fields=("trip", "date"), name="unique_itinerary_day"
            ),
        ),
        migrations.AddIndex(
            model_name="itineraryentry",
            index=models.Index(
                fields=["trip", "day", "position"],
                name="itinerary_i_trip_id_dd3beb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itineraryentry",
            index=models.Index(fields=["trip", "starts_at"], name="itinerary_i_trip_id_e06746_idx"),
        ),
        migrations.AddConstraint(
            model_name="itineraryentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("proposal__isnull", False)),
                fields=("proposal",),
                name="one_entry_per_proposal",
            ),
        ),
        migrations.AddConstraint(
            model_name="itineraryentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    ("starts_at__isnull", True),
                    ("ends_at__gte", models.F("starts_at")),
                    _connector="OR",
                ),
                name="itinerary_valid_times",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["trip", "pinned", "created_at"],
                name="itinerary_n_trip_id_c2da35_idx",
            ),
        ),
    ]
