"""Ski bot copy (Rioplatense Spanish, voseo); the only Spanish in the ski api."""

HELP_NIEVE = "/viaje nieve — cómo está la nieve (o /viaje nieve catedral 120 15 para reportar)"

SNOW_HEADER = "❄️ Nieve:"
SNOW_LINE = "{resort}: {parts} ({age})"
SNOW_BASE = "{base} cm de base"
SNOW_NEW = "{new} cm nuevos en 24 h"
SNOW_TEMP = "{temp} °C"
SNOW_LIFTS = "{open}/{total} medios abiertos"
SNOW_FORECAST = " · pronóstico {forecast} cm en 3 días"
SNOW_STALE = " ⚠️ dato viejo"
SNOW_NO_DETAIL = "sin detalle"
AGE_HOURS = "hace {hours} h"
AGE_MINUTES = "recién"
NO_RESORTS = "Este viaje todavía no tiene centros de ski. Sumalos en {url}"
NO_REPORT = "{resort}: sin datos todavía"
NO_TRIP = "Todavía no hay un viaje elegido para el grupo 🏖️"
NOT_SKI_TRIP = "Este viaje no es de ski 🏖️"
MANUAL_SAVED = "Gracias {name}, anoté {base} cm en {resort} 🙌"
RESORT_UNKNOWN = "No encontré ese centro. Los del viaje: {resorts}"
NIEVE_USAGE = "Usalo así: /viaje nieve catedral 120 15"
RATE_LIMITED = "Ya hubo varios reportes de ese centro en la última hora. Probá más tarde 🙏"
