# Generated by Django 5.2.17 on 2026-10-01 19:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("proposals", "0001_initial"),
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskSequence",
            fields=[
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="trips.trip",
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                ("kind", models.CharField(default="todo", max_length=8)),
                ("title", models.CharField(max_length=200)),
                ("notes", models.TextField(default="", max_length=2000)),
                ("due_on", models.DateField(null=True)),
                ("status", models.CharField(default="open", max_length=8)),
                ("quantity", models.PositiveSmallIntegerField(null=True)),
                ("source", models.CharField(default="manual", max_length=12)),
                ("nudge_count", models.PositiveSmallIntegerField(default=0)),
                ("last_nudged_at", models.DateTimeField(null=True)),
                ("done_at", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="proposals.proposal",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["trip", "status"], name="logistics_t_trip_id_9f0163_idx"),
                    models.Index(
                        fields=["status", "due_on"],
                        name="logistics_t_status_127328_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("trip", "number"), name="unique_task_number"),
                    models.UniqueConstraint(
                        condition=models.Q(("proposal__isnull", False)),
                        fields=("proposal", "kind"),
                        name="one_task_per_proposal_kind",
                    ),
                ],
            },
        ),
    ]
