# Generated by Django 5.2.17 on 2026-10-01 19:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0001_initial"),
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("template_key", models.CharField(max_length=32)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="trips.trip"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "person", "template_key"),
                        name="unique_packing_application",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PackingEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("section", models.CharField(default="custom", max_length=32)),
                ("item_key", models.CharField(max_length=64, null=True)),
                ("label", models.CharField(max_length=120)),
                ("quantity", models.PositiveSmallIntegerField(null=True)),
                ("packed", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="trips.trip"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["trip", "person"], name="logistics_p_trip_id_059ad8_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("item_key__isnull", False)),
                        fields=("trip", "person", "item_key"),
                        name="unique_packing_item",
                    )
                ],
            },
        ),
    ]
