/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/trips/{trip_id}/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          owner?: string;
          kind?: string;
          status?: string[];
        };
        header?: never;
        path: {
          trip_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["TaskOut"][];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trip_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TaskCreate"];
        };
      };
      responses: {
        /** @description Success */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["TaskOut"];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          task_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          task_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TaskPatch"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["TaskOut"];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/trips/{trip_id}/packing/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trip_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PackingListOut"];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trips/{trip_id}/packing/me/apply": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trip_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            template_key: string;
          };
        };
      };
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PackingListOut"];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trips/{trip_id}/packing/me/entries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trip_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["PackingCreate"];
        };
      };
      responses: {
        /** @description Success */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PackingEntryOut"];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/packing_entries/{entry_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          entry_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          entry_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["PackingPatch"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PackingEntryOut"];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/trips/{trip_id}/packing/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trip_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              person: components["schemas"]["PersonRefOut"];
              packed: number;
              total: number;
            }[];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trips/{trip_id}/budget": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trip_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BudgetOut"];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trips/{trip_id}/budget/fx_rates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trip_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            rates: {
              [key: string]: string;
            };
          };
        };
      };
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BudgetOut"];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trips/{trip_id}/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          kind?: string;
        };
        header?: never;
        path: {
          trip_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["DocumentOut"][];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/documents/{document_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          document_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          document_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["DocumentPatch"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["DocumentOut"];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    PersonRefOut: {
      person_id: string;
      display_name: string;
    };
    TaskOut: {
      id: string;
      trip_id: string;
      number: number;
      /** @enum {string} */
      kind: "todo" | "bring" | "booking";
      title: string;
      notes: string;
      owner: components["schemas"]["PersonRefOut"] | null;
      due_on: string | null;
      /** @enum {string} */
      status: "open" | "done" | "blocked";
      quantity: number | null;
      proposal_id: string | null;
      /** @enum {string} */
      source: "manual" | "proposal" | "template";
      nudge_count: number;
      done_at: string | null;
      done_by: components["schemas"]["PersonRefOut"] | null;
      overdue: boolean;
      created_at: string;
      updated_at: string;
    };
    TaskCreate: {
      title: string;
      /** @enum {string} */
      kind?: "todo" | "bring" | "booking";
      notes?: string;
      owner_id?: string | null;
      due_on?: string | null;
      quantity?: number | null;
    };
    TaskPatch: {
      title?: string;
      /** @enum {string} */
      kind?: "todo" | "bring" | "booking";
      notes?: string;
      owner_id?: string | null;
      due_on?: string | null;
      quantity?: number | null;
      /** @enum {string} */
      status?: "open" | "done" | "blocked";
    };
    PackingEntryOut: {
      id: string;
      section: string;
      item_key: string | null;
      label: string;
      quantity: number | null;
      packed: boolean;
      position: number;
    };
    PackingListOut: {
      templates_available: {
        key: string;
        label: string;
      }[];
      applied: string[];
      sections: {
        key: string;
        label: string;
        entries: components["schemas"]["PackingEntryOut"][];
      }[];
      progress: {
        packed: number;
        total: number;
      };
    };
    PackingCreate: {
      label: string;
      section?: string;
      quantity?: number | null;
    };
    PackingPatch: {
      label?: string;
      quantity?: number | null;
      packed?: boolean;
      position?: number;
    };
    BudgetLineOut: {
      proposal_id: string;
      title: string;
      category: string;
      status: string;
      price_basis: string;
      original_amount: string;
      original_currency: string;
      nights: number | null;
      nights_assumed: boolean;
      amount: string | null;
      per_person: string | null;
    };
    BudgetOut: {
      currency: string;
      participants: number;
      /** @enum {string} */
      participants_basis: "in" | "in_maybe" | "minimum";
      lines: components["schemas"]["BudgetLineOut"][];
      by_category: {
        [key: string]: string;
      };
      committed: string;
      expected: string;
      total: string;
      per_person: string;
      remainder: string;
      unconverted: components["schemas"]["BudgetLineOut"][];
      missing_price: {
        proposal_id: string;
        title: string;
      }[];
      fx_rates: {
        [key: string]: string;
      };
      gastito_url: string | null;
    };
    DocumentOut: {
      id: string;
      trip_id: string;
      title: string;
      /** @enum {string} */
      kind: "reservation" | "ticket" | "insurance" | "id" | "photo" | "other";
      mime: string;
      size: number;
      /** @enum {string} */
      visibility: "crew" | "owner_only";
      owner: components["schemas"]["PersonRefOut"] | null;
      uploader: components["schemas"]["PersonRefOut"];
      valid_until: string | null;
      proposal_id: string | null;
      created_at: string;
      download_path: string;
      can_delete: boolean;
    };
    DocumentPatch: {
      title?: string;
      /** @enum {string} */
      kind?: "reservation" | "ticket" | "insurance" | "id" | "photo" | "other";
      /** @enum {string} */
      visibility?: "crew" | "owner_only";
      valid_until?: string | null;
      proposal_id?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
