# Generated by Django 5.2.17 on 2026-10-01 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("linkpreview", "0001_initial"),
        ("messaging", "0006_outboundmessage_subject_id_255"),
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("lodging", "Lodging"),
                            ("transport", "Transport"),
                            ("activity", "Activity"),
                            ("food", "Food"),
                            ("gear", "Gear"),
                            ("destination", "Destination"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("discussing", "Discussing"),
                            ("chosen", "Chosen"),
                            ("booked", "Booked"),
                            ("discarded", "Discarded"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("note", models.TextField(blank=True, default="", max_length=2000)),
                (
                    "canonical_url",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "est_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_basis",
                    models.CharField(
                        choices=[
                            ("total", "Total"),
                            ("per_person", "Per Person"),
                            ("per_night", "Per Night"),
                        ],
                        default="total",
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                (
                    "booking_ref",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("chosen_at", models.DateTimeField(blank=True, null=True)),
                ("booked_at", models.DateTimeField(blank=True, null=True)),
                ("discarded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "classified_by",
                    models.CharField(
                        choices=[("rules", "Rules"), ("llm", "Llm"), ("user", "User")],
                        default="user",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link_preview",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="linkpreview.linkpreview",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="messaging.inboundmessage",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="messaging.inboundmessage",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="proposals.proposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.SmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="proposals.proposal",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="messaging.inboundmessage",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["trip", "status"], name="proposals_p_trip_id_d134d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["trip", "category"], name="proposals_p_trip_id_34544d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("canonical_url__isnull", False)),
                fields=("trip", "canonical_url"),
                name="unique_trip_canonical_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("starts_on__isnull", True),
                    ("ends_on__isnull", True),
                    ("ends_on__gte", models.F("starts_on")),
                    _connector="OR",
                ),
                name="proposal_ends_after_starts",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("est_price__isnull", True), ("est_price__gte", 0), _connector="OR"
                ),
                name="proposal_price_not_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["proposal", "created_at"], name="proposals_c_proposa_616748_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("proposal", "person"), name="unique_vote_per_person"
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__in", [-1, 0, 1])), name="vote_value_valid"
            ),
        ),
    ]
