from typing import Protocol

from crews.domain import CrewSummary


class CrewStore(Protocol):
    def find_crew_id_by_chat_id(self, chat_id: str) -> str | None: ...

    def create_crew(self, name: str, chat_id: str) -> str: ...

    def ensure_admin(self, crew_id: str, phone: str) -> None:
        """Get-or-create the person for ``phone`` and make them an active admin of the crew."""
        ...

    def phone_has_membership_or_invite(self, phone: str) -> bool: ...

    def summaries_for(self, person_id: str) -> list[CrewSummary]: ...

    def accept_pending_invites(self, person_id: str, phone: str) -> int: ...
