# Generated by Django 5.2.17 on 2026-10-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_jid", models.CharField(max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("otp", "Otp"),
                            ("card", "Card"),
                            ("reminder", "Reminder"),
                            ("reply", "Reply"),
                        ],
                        max_length=16,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "dedupe_key",
                    models.CharField(blank=True, max_length=200, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("gowa_message_id", models.CharField(blank=True, max_length=128)),
                ("reply_to_message_id", models.CharField(blank=True, max_length=128)),
                ("subject_type", models.CharField(blank=True, max_length=64)),
                ("subject_id", models.CharField(blank=True, max_length=64)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
