# Generated by Django 5.2.17 on 2026-10-01 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("locked_until", models.DateTimeField()),
                ("locked_by", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="InboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=128)),
                ("gowa_message_id", models.CharField(max_length=128)),
                ("event", models.CharField(max_length=32)),
                ("chat_id", models.CharField(max_length=64)),
                ("sender_jid", models.CharField(blank=True, max_length=64)),
                ("sender_lid", models.CharField(blank=True, max_length=64)),
                ("sender_name", models.CharField(blank=True, max_length=120)),
                ("body", models.TextField(blank=True)),
                ("replied_to_id", models.CharField(blank=True, max_length=128)),
                ("raw", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("ignored", "Ignored"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("outcome", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status"], name="messaging_i_status_156370_idx"),
                    models.Index(fields=["chat_id"], name="messaging_i_chat_id_3352bd_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device_id", "gowa_message_id"),
                        name="unique_inbound_device_message",
                    )
                ],
            },
        ),
    ]
