# Generated by Django 5.2.17 on 2026-10-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_joblock_inboundmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundmessage",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="outboundmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=16,
            ),
        ),
    ]
