# Generated by Django 5.2.17 on 2026-10-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0003_outbound_sending_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundmessage",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
