# Generated by Django 5.2.17 on 2026-10-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0004_inboundmessage_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundmessage",
            name="mentions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
