# Generated by Django 5.2.17 on 2026-10-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0005_outboundmessage_mentions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboundmessage",
            name="subject_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
