# Generated by Django 5.2.17 on 2026-10-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0006_outboundmessage_subject_id_255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboundmessage",
            name="subject_id",
            field=models.TextField(blank=True),
        ),
    ]
