# Generated by Django 5.2.17 on 2026-10-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
