# Generated by Django 5.2.17 on 2026-10-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crews", "0002_invite_cancelled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappgrouplink",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
