# Generated by Django 5.2.17 on 2026-10-01 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crews", "0003_whatsappgrouplink_last_synced_at"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="default_trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="trips.trip",
            ),
        ),
    ]
