# Generated by Django 5.2.17 on 2026-10-01 17:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crews", "0003_whatsappgrouplink_last_synced_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("type", models.CharField(default="generic", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idea", "Idea"),
                            ("planning", "Planning"),
                            ("booked", "Booked"),
                            ("ongoing", "Ongoing"),
                            ("done", "Done"),
                        ],
                        default="planning",
                        max_length=16,
                    ),
                ),
                ("start_on", models.DateField(blank=True, null=True)),
                ("end_on", models.DateField(blank=True, null=True)),
                (
                    "destination_label",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("fx_rates", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="crews.crew",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rsvp",
                    models.CharField(
                        choices=[
                            ("in", "In"),
                            ("maybe", "Maybe"),
                            ("out", "Out"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("trip", "person"), name="unique_trip_person")
                ],
            },
        ),
    ]
