# Generated by Django 5.2.17 on 2026-10-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="trips/covers/"),
        ),
        migrations.AddField(
            model_name="trip",
            name="cover_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
