/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["ops_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Csrf */
        get: operations["identity_api_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Otp
         * @description Always answers the same 202 for valid phones.
         *
         *     400 codes: `invalid_phone`, `invalid_request`. 403: `csrf_failed`.
         */
        post: operations["identity_api_request_otp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Otp
         * @description Logs the person in.
         *
         *     400 codes: `invalid_phone`, `invalid_code`, `expired_code`, `too_many_attempts`,
         *     `invalid_request`. 403: `csrf_failed`.
         */
        post: operations["identity_api_verify_otp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["identity_api_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["identity_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crews/{crew_id}/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["trips_api_list_trips"];
        put?: never;
        /**
         * Create Trip
         * @description 400 codes: `invalid_request`. 404: `not_found` (not a member of the crew).
         */
        post: operations["trips_api_create_trip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["trips_api_get_trip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Trip
         * @description Any active member of the crew may update. 400 codes: `invalid_request`.
         */
        patch: operations["trips_api_update_trip"];
        trace?: never;
    };
    "/api/trips/{trip_id}/participation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Participation
         * @description Sets the caller's own RSVP, creating their participation when missing.
         */
        put: operations["trips_api_set_participation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ski/resorts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resorts */
        get: operations["ski_api_list_resorts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/ski": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["ski_api_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/ski/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conditions */
        get: operations["ski_api_conditions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/ski/resorts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Resort */
        post: operations["ski_api_add_resort"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/ski/resorts/{resort_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Resort */
        delete: operations["ski_api_remove_resort"];
        options?: never;
        head?: never;
        /** Patch Resort */
        patch: operations["ski_api_patch_resort"];
        trace?: never;
    };
    "/api/trips/{trip_id}/ski/resorts/{resort_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["ski_api_list_reports"];
        put?: never;
        /** Create Report */
        post: operations["ski_api_create_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/ski/passes/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set My Pass */
        put: operations["ski_api_set_my_pass"];
        post?: never;
        /** Delete My Pass */
        delete: operations["ski_api_delete_my_pass"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/ski/gear/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set My Gear */
        put: operations["ski_api_set_my_gear"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/ski_profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["ski_api_get_profile"];
        /** Put Profile */
        put: operations["ski_api_put_profile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HealthChecks */
        HealthChecks: {
            /**
             * Db
             * @enum {string}
             */
            db: "ok" | "error";
            /**
             * Media
             * @enum {string}
             */
            media: "ok" | "error";
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            checks: components["schemas"]["HealthChecks"];
        };
        /** CsrfOut */
        CsrfOut: {
            /** Csrf Token */
            csrf_token: string;
        };
        /** OtpRequestOut */
        OtpRequestOut: {
            /**
             * Status
             * @constant
             */
            status: "sent";
            /** Retry After Seconds */
            retry_after_seconds: number;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** OtpRequestIn */
        OtpRequestIn: {
            /** Phone */
            phone: string;
        };
        /** OtpVerifyOut */
        OtpVerifyOut: {
            person: components["schemas"]["PersonOut"];
        };
        /** PersonOut */
        PersonOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Phone */
            phone: string;
            /** Display Name */
            display_name: string;
            /** Locale */
            locale: string;
        };
        /** OtpVerifyIn */
        OtpVerifyIn: {
            /** Phone */
            phone: string;
            /** Code */
            code: string;
        };
        /** CrewSummaryOut */
        CrewSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "member";
            /** Gastito Group Url */
            gastito_group_url: string | null;
            /** Default Trip Id */
            default_trip_id: string | null;
        };
        /** MeOut */
        MeOut: {
            person: components["schemas"]["PersonOut"];
            /** Crews */
            crews: components["schemas"]["CrewSummaryOut"][];
        };
        /** TripSummaryOut */
        TripSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "idea" | "planning" | "booked" | "ongoing" | "done";
            /** Start On */
            start_on: string | null;
            /** End On */
            end_on: string | null;
            /** Destination Label */
            destination_label: string;
        };
        /** ParticipantOut */
        ParticipantOut: {
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /** Display Name */
            display_name: string;
            /**
             * Rsvp
             * @enum {string}
             */
            rsvp: "in" | "maybe" | "out" | "pending";
        };
        /** TripOut */
        TripOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Crew Id
             * Format: uuid
             */
            crew_id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "idea" | "planning" | "booked" | "ongoing" | "done";
            /** Start On */
            start_on: string | null;
            /** End On */
            end_on: string | null;
            /** Destination Label */
            destination_label: string;
            /** Timezone */
            timezone: string;
            /** Currency */
            currency: string;
            /** Fx Rates */
            fx_rates: {
                [key: string]: string;
            };
            /** Modules */
            modules: string[];
            /** Participants */
            participants: components["schemas"]["ParticipantOut"][];
            /**
             * My Rsvp
             * @enum {string}
             */
            my_rsvp: "in" | "maybe" | "out" | "pending";
        };
        /** TripCreateIn */
        TripCreateIn: {
            /** Name */
            name: string;
            /**
             * Type
             * @default generic
             */
            type: string;
            /** Start On */
            start_on?: string | null;
            /** End On */
            end_on?: string | null;
            /**
             * Destination Label
             * @default
             */
            destination_label: string;
            /**
             * Currency
             * @default USD
             */
            currency: string;
        };
        /**
         * TripPatchIn
         * @description Every field optional; only the ones sent are applied (``null`` clears a date).
         */
        TripPatchIn: {
            /** Name */
            name?: string | null;
            /** Type */
            type?: string | null;
            /** Status */
            status?: ("idea" | "planning" | "booked" | "ongoing" | "done") | null;
            /** Start On */
            start_on?: string | null;
            /** End On */
            end_on?: string | null;
            /** Destination Label */
            destination_label?: string | null;
            /** Currency */
            currency?: string | null;
            /** Fx Rates */
            fx_rates?: {
                [key: string]: number | string;
            } | null;
        };
        /** ParticipantIn */
        ParticipantIn: {
            /**
             * Rsvp
             * @enum {string}
             */
            rsvp: "in" | "maybe" | "out" | "pending";
        };
        /** PersonRefOut */
        PersonRefOut: {
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /** Display Name */
            display_name: string;
        };
        /** ResortOut */
        ResortOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Country
             * @enum {string}
             */
            country: "AR" | "CL";
            /** Region */
            region: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Base Elev M */
            base_elev_m: number;
            /** Summit Elev M */
            summit_elev_m: number;
            /** Website Url */
            website_url: string;
        };
        /** SnowReportOut */
        SnowReportOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "open_meteo" | "manual";
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            base_cm: number | null;
            new_24h_cm: number | null;
            forecast_72h_cm: number | null;
            temp_c: number | null;
            lifts_open: number | null;
            lifts_total: number | null;
            runs_open: number | null;
            runs_total: number | null;
            /** Status Text */
            status_text: string;
            reporter: components["schemas"]["PersonRefOut"] | null;
            /** Stale */
            stale: boolean;
            /** Age Hours */
            age_hours: number;
        };
        /** TripResortOut */
        TripResortOut: {
            resort: components["schemas"]["ResortOut"];
            nights: number | null;
            /** Position */
            position: number;
            latest_report: components["schemas"]["SnowReportOut"] | null;
        };
        /** ConditionsResortOut */
        ConditionsResortOut: {
            /**
             * Resort Id
             * Format: uuid
             */
            resort_id: string;
            /** Name */
            name: string;
            latest_report: components["schemas"]["SnowReportOut"] | null;
        };
        /** SkiConditionsOut */
        SkiConditionsOut: {
            /** Resorts */
            resorts: components["schemas"]["ConditionsResortOut"][];
        };
        /** PassRowOut */
        PassRowOut: {
            person: components["schemas"]["PersonRefOut"];
            resort_id: string | null;
            /** Product */
            product: string;
            days: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "needed" | "bought" | "season_pass" | "not_needed";
            price: string | null;
            /** Currency */
            currency: string;
        };
        /** MissingPassOut */
        MissingPassOut: {
            person: components["schemas"]["PersonRefOut"];
            resort_id: string | null;
        };
        /** PassSummaryOut */
        PassSummaryOut: {
            /** Rows */
            rows: components["schemas"]["PassRowOut"][];
            /** Missing */
            missing: components["schemas"]["MissingPassOut"][];
        };
        /** GearRowOut */
        GearRowOut: {
            person: components["schemas"]["PersonRefOut"];
            /**
             * Item
             * @enum {string}
             */
            item: "skis" | "board" | "boots" | "poles" | "helmet" | "goggles" | "jacket" | "pants" | "other";
            /**
             * Mode
             * @enum {string}
             */
            mode: "own" | "rent" | "borrow";
            price: string | null;
            /** Currency */
            currency: string;
            /** Note */
            note: string;
        };
        /** SharedSizeOut */
        SharedSizeOut: {
            person: components["schemas"]["PersonRefOut"];
            boot_size_eu: number | null;
            height_cm: number | null;
            weight_kg: number | null;
        };
        /** GearRollupOut */
        GearRollupOut: {
            /** Rows */
            rows: components["schemas"]["GearRowOut"][];
            /** Rent Counts */
            rent_counts: {
                [key: string]: number;
            };
            /** Sizes */
            sizes: components["schemas"]["SharedSizeOut"][];
            /** Sizes Hidden */
            sizes_hidden: number;
        };
        /** LevelGroupOut */
        LevelGroupOut: {
            /**
             * Discipline
             * @enum {string}
             */
            discipline: "ski" | "snowboard" | "both";
            /**
             * Level
             * @enum {string}
             */
            level: "first_time" | "beginner" | "intermediate" | "advanced" | "expert";
            /** People */
            people: components["schemas"]["PersonRefOut"][];
        };
        /** SkiOverviewOut */
        SkiOverviewOut: {
            /** Resorts */
            resorts: components["schemas"]["TripResortOut"][];
            passes: components["schemas"]["PassSummaryOut"];
            gear: components["schemas"]["GearRollupOut"];
            /** Levels */
            levels: components["schemas"]["LevelGroupOut"][];
        };
        /** SkiProfileOut */
        SkiProfileOut: {
            /**
             * Discipline
             * @enum {string}
             */
            discipline: "ski" | "snowboard" | "both";
            /**
             * Level
             * @enum {string}
             */
            level: "first_time" | "beginner" | "intermediate" | "advanced" | "expert";
            /** Owns Gear */
            owns_gear: boolean;
            boot_size_eu: number | null;
            height_cm: number | null;
            weight_kg: number | null;
            /** Share Sizes With Trip */
            share_sizes_with_trip: boolean;
        };
        /** SkiProfileIn */
        SkiProfileIn: {
            /**
             * Discipline
             * @enum {string}
             */
            discipline: "ski" | "snowboard" | "both";
            /**
             * Level
             * @enum {string}
             */
            level: "first_time" | "beginner" | "intermediate" | "advanced" | "expert";
            /** Owns Gear */
            owns_gear: boolean;
            boot_size_eu: number | null;
            height_cm: number | null;
            weight_kg: number | null;
            /** Share Sizes With Trip */
            share_sizes_with_trip: boolean;
        };
        /** TripResortIn */
        TripResortIn: {
            /**
             * Resort Id
             * Format: uuid
             */
            resort_id: string;
            nights?: number | null;
        };
        /** TripResortPatchIn */
        TripResortPatchIn: {
            nights?: number | null;
            position?: number | null;
        };
        /** ManualReportIn */
        ManualReportIn: {
            base_cm?: number | null;
            new_24h_cm?: number | null;
            temp_c?: number | null;
            lifts_open?: number | null;
            lifts_total?: number | null;
            runs_open?: number | null;
            runs_total?: number | null;
            status_text?: string | null;
        };
        /** PassIn */
        PassIn: {
            resort_id?: string | null;
            product?: string | null;
            days?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "needed" | "bought" | "season_pass" | "not_needed";
            price?: string | null;
            currency?: string | null;
        };
        /** GearItemIn */
        GearItemIn: {
            /**
             * Item
             * @enum {string}
             */
            item: "skis" | "board" | "boots" | "poles" | "helmet" | "goggles" | "jacket" | "pants" | "other";
            /**
             * Mode
             * @enum {string}
             */
            mode: "own" | "rent" | "borrow";
            price?: string | null;
            currency?: string | null;
            note?: string | null;
        };
        /** GearIn */
        GearIn: {
            /** Items */
            items: components["schemas"]["GearItemIn"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ops_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    identity_api_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfOut"];
                };
            };
        };
    };
    identity_api_request_otp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequestIn"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpRequestOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    identity_api_verify_otp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerifyIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpVerifyOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    identity_api_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    identity_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    trips_api_list_trips: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                crew_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripSummaryOut"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    trips_api_create_trip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                crew_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    trips_api_get_trip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    trips_api_update_trip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripPatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    trips_api_set_participation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ski_api_list_resorts: {
        parameters: {
            query?: {
                country?: ("AR" | "CL") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResortOut"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ski_api_overview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkiOverviewOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ski_api_conditions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkiConditionsOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ski_api_add_resort: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripResortIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResortOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ski_api_remove_resort: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                resort_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ski_api_patch_resort: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                resort_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripResortPatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResortOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ski_api_list_reports: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                resort_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnowReportOut"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ski_api_create_report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                resort_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualReportIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnowReportOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ski_api_set_my_pass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PassIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassRowOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ski_api_delete_my_pass: {
        parameters: {
            query?: {
                resort_id?: string | null;
            };
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ski_api_set_my_gear: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GearIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GearRowOut"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ski_api_get_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkiProfileOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ski_api_put_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkiProfileIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkiProfileOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
