import type { TripCoverScene } from "@/ui/illustrations/TripCoverArt";
import manifest from "./manifest.json";

export type AmbientClip = {
  mp4: string;
  poster: string;
  hash: string;
  credit: { author: string; source: string; license: string };
};

/** Kill switch: false keeps the posters but never mounts a <video> (CDN terms, Range trouble). */
export const AMBIENT_VIDEO_ENABLED = true;

// manifest.json is generated by `pnpm ambient:build` (scripts/ambient/build.mjs); empty means no clips.
const clips = manifest.clips as Partial<Record<TripCoverScene, AmbientClip>>;

/** The self-hosted loop for a scene, or `null` when there is none (the illustration shows instead). */
export function ambientClip(scene: TripCoverScene): AmbientClip | null {
  return clips[scene] ?? null;
}
