# Generated by Django 5.2.17 on 2026-10-01 19:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import documents.models
import documents.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("proposals", "0001_initial"),
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultQuota",
            fields=[
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="trips.trip",
                    ),
                ),
                ("plaintext_bytes", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("kind", models.CharField(default="other", max_length=16)),
                (
                    "file",
                    models.FileField(
                        max_length=200,
                        storage=documents.storage.EncryptedFileSystemStorage(),
                        upload_to=documents.models.vault_path,
                    ),
                ),
                ("original_name", models.CharField(default="", max_length=200)),
                ("mime", models.CharField(max_length=64)),
                ("size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("visibility", models.CharField(default="crew", max_length=12)),
                ("valid_until", models.DateField(null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="proposals.proposal",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="trips.trip",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["trip", "kind"], name="documents_d_trip_id_e5d84d_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("visibility", "owner_only"), _negated=True),
                            ("owner__isnull", False),
                            _connector="OR",
                        ),
                        name="private_document_owner_required",
                    )
                ],
            },
        ),
    ]
